### ISSUE TITLE
Documentation standards.

### ISSUE THREAD

**Issue by dantleech** [sulu-cmf/sulu-docs#6]
We should adopt the standards used by Symfony documentors:

http://symfony.com/doc/current/contributing/documentation/standards.html

For example no lines exeeding 85 characters, line breaks after a title etc.

**Comment by danrot** [comment]
Do we need an issue for that? Actually I don't think so... Can we close it?

**Comment by dantleech** [comment]
I think we should formalize it, and add a small "contributing" section to the docs.

**Comment by dantleech** [comment]
I guess it would include the PR templates etc. too.
